Repository TableauBits/Kalimba, pull requests merged in 2021-09, with the labels that each got.

#21 Support des chansons
  package-lock.json
  package.json
  src/REST/controllers/dashboard/constitution-graph.ejs
  src/REST/controllers/dashboard/dashboard.ts
  src/WebSocket/event-handler.ts
  src/WebSocket/module.ts
  src/WebSocket/modules/constitution-manager.ts
  src/WebSocket/modules/constitution.ts
  src/WebSocket/modules/song.ts
  src/WebSocket/modules/user.ts
Labels: enhancement, WebSocket API, Communications protocol

#22 Passage de Hang à Chelys
  package-lock.json
  package.json
  src/WebSocket/event-handler.ts
  src/WebSocket/module.ts
  src/WebSocket/modules/constitution-manager.ts
  src/WebSocket/modules/constitution.ts
  src/WebSocket/modules/song.ts
  src/WebSocket/modules/telemetry.ts
  src/WebSocket/modules/user.ts
  src/WebSocket/utility.ts
Labels: Communications protocol

#23 Fix/heroku deps
  .npmrc-ci
  package.json
Labels: tooling
