Repository TableauBits/Kalimba, pull requests merged in 2024-01, with the labels that each got.

#53 Ajout du param ENVIRONMENT pour pouvoir changer l'adresse de connexion en production
  .env.template
  .github/workflows/deploy.yaml
  .gitignore
  src/index.ts
Labels: bug, maintenance

#55 Mise à jour de la config de déploiement pour que Fly.io soit content
  .github/workflows/deploy.yaml
  .gitignore
  Dockerfile
  fly.toml
  src/REST/controllers/keep-alive/keep-alive.ts
  src/REST/endpoint-creation.ts
  src/index.ts
Labels: tooling, maintenance

#56 Vaporwave (Slowed + Reverb)
  .github/workflows/deploy.yaml
  .gitignore
  Dockerfile
  fly.toml
  src/REST/controllers/keep-alive/keep-alive.ts
  src/REST/endpoint-creation.ts
  src/index.ts
Labels: release

#57 Fix de la configuration fly io pour que kalimba soit toujours up et que les lectures n'explosent pas
  fly.toml
Labels: bug, deployment
