Repository TableauBits/Kalimba, pull requests merged in 2025-02, with the labels that each got.

#63 Déploiement via Github release au lieu de la branche release
  .github/workflows/deploy.yaml
Labels: deployment

#62 Ajout d'une feature admin pour dump la DB
  package-lock.json
  package.json
  src/REST/controllers/dashboard/template.ejs
  src/REST/controllers/dump-db.ts
  src/REST/endpoint-creation.ts
  src/index.ts
Labels: enhancement, tooling, HTTP API

#64 Légers tweaks pour un meilleur dump de la DB
  src/REST/controllers/dashboard/template.ejs
  src/REST/controllers/dump-db.ts
Labels: maintenance
